# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

build:
   image: latest

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF
# formats:
#    - pdf
#    - epub

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.11
   install:
      - method: pip
        path: .
      - requirements: requirements.txt, docs/requirements.txt
   system_packages: true
