package:
  name: cbadc
  version: 0.2.3

source:
  git_rev: v0.2.3
  git_url: https://github.com/hammal/cbadc.git

requirements:
  build:
    - python>=3.8
    - setuptools

  run:
    - python
    - numpy>=1.24.4
    - scipy>=1.10.1
    - pip
    - tqdm>=4.61.0
    - requests>=2.25.1
    - pandas>=1.3.4
    - matplotlib>=3.4.3
    - xlrd>=1.0.0
    - sympy>=1.9
    - mpmath>=1.1
    - jinja2>=3
    # - ltspice>=1.0.6

test:
  imports:
    - cbadc

about:
  home: https://github.com/hammal/cbadc.git
