package:
  name: cbadc
  version: 0.2.2

source:
  git_rev: v0.2.2
  git_url: https://github.com/hammal/cbadc.git

requirements:
  build:
    - python>=3.8
    - setuptools

  run:
    - python
    - numpy>=1.20.1
    - scipy>=1.7.1
    - tqdm>=4.61.0
    - requests>=2.25.1
    - pytest
    - pytest-benchmark
    - pytest-cov
    - typing-extensions
    - pandas>=1.3.4
    - matplotlib>=3.4.3
    - xlrd>=1.0.0
    - sympy>=1.9
    - mpmath>=1.1
    - jinja2>=3
    - pre-commit>=2.17.0
    - Pillow>=9.1.1
    - pyarrow>=8.0.0
    - inform>=1.26.0
    # - ltspice>=1.0.6

test:
  imports:
    - cbadc

about:
  home: https://github.com/hammal/cbadc.git
