# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build for manylinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Initalize submodules
      run: >-
        git submodule init;
        rm -rf tests/AnalogToDigital;
        ln -s PythonADC/AnalogToDigital tests/;
    - name: Upgrade pip
      run: >-
        python -m
        pip install
        --upgrade
        pip
    - name: install Tox
      run:
        python -m pip install tox;
    - name: UnitTest with Tox
      run:
        tox -e py$(echo ${PYTHON_V} | sed 's/.//g');
      env:
        PYTHON_V: ${{ matrix.python-version }}
    - name: Build manylinux Python wheels for x86_64
      uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux1_x86_64
      with:
        python-versions: 'cp38-cp38'
        build-requirements: 'cython numpy scipy'
    - name: Publish distribution 📦 to Test PyPI
      # if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      # if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
