# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: unit testing

on: workflow_call

jobs:
  ngspice-simulations:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hammal/cbadc:develop
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: update pip and install dependencies
        run: |
          python -m pip install --upgrade pip pytest pytest-parallel pytest-cov pytest-benchmark
      - name: Run circuit test
        run: |
          cd cbadc && \ 
          pytest tests/circuit
