
name: building tutorials

on:
  push:
    branches:
      - 'master'
      - 'develop'
  workflow_run:
      workflows: ['linting, doc, and unit testing']
      types:
        - completed

jobs:
  build-tutorials:
    name: "Build the tutorials for the docs"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install -r docs/requirements.txt

      - name: Execute the notebooks
        working-directory: docs
        run: |
          make html

      - uses: actions/upload-artifact@v2
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/source/tutorials

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
