# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: unit testing

on: workflow_call

jobs:
  lint_and_unit_tests:
    strategy:
      matrix:
        python-version: ["3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: update pip
        run: |
            python -m pip install --upgrade pip pytest pytest-parallel pytest-cov pytest-benchmark
      - name: Install cbadc dependencies
        run: |
          pip install -r requirements.txt;
          pip install .
      - name: Run performance tests
        run: |
          pytest --workers auto tests/performance_validation

    #   - name: Upload Unit Test Results
    #     if: always()
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: Unit Test Results (Python ${{ matrix.python-version }})
    #       path: pytest-unittests.xml

    #   - name: Upload Doc Test Results
    #     if: always()
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: Unit Test Results (Python ${{ matrix.python-version }})
    #       path: pytest-doctests.xml
