# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: performance validation, compiling tutorials, and benchmarking

on: [pull_request]

jobs:

  performance_validation:
    timeout-minutes: 3000
    runs-on: [self-hosted]
    strategy:
      fail-fast: true
      matrix:
        part: [
          "full-test",
          "full-test-switch-cap-control",
          "full-test-simulator",
          "full-test-fir-filter"
        ]
    # needs: doc_and_unit_tests
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Full performance validation
        run: tox -e ${{ matrix.part }}

  circuit_level_validation:
    timeout-minutes: 3000
    runs-on: [self-hosted]
    # needs: doc_and_unit_tests
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Validate python circuit-level simulations
        run: tox -e circuit-level-python

  benchmarks:
    timeout-minutes: 3000
    runs-on: [self-hosted]
    # needs: doc_and_unit_tests
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Benchmarking
        run: tox -e benchmark
