name: unit testing

on: workflow_call

jobs:
  lint_and_unit_tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-caching: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run doctests
        run: uv run pytest --junitxml=pytest-unittests.xml --doctest-modules src/cbadc

      - name: Run unittests
        run: uv run pytest --junitxml=pytest-unittests.xml tests/unittest

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results (Python ${{ matrix.python-version }})
          path: pytest-unittests.xml
