# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: unit test cbadc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  tox_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Initialize submodules
        run: >-
          git submodule init;
          rm -rf tests/AnalogToDigital;
          ln -s PythonADC/AnalogToDigital tests/;
    
      - name: Upgrade pip
        run: >-
          python -m
          pip install
          --upgrade
          pip

      - name: Install Tox
        run:
          python -m pip install tox;

      - name: UnitTest
        run: tox -e py38
        env: 
          CYTHON: True